services:
  - type: worker
    name: telegram-force-join-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MAIN_GROUP_ID
        sync: false
      - key: BACKUP_GROUP_ID
        sync: false
